[package]
name = "likemark-cli"
version = "0.1.0"
authors = ["team-chiru <team-chiru@protonmail.com>"]

[dependencies]
clap = {version = "2.32", features = [ "yaml", "suggestions", "color" ]}
hyper = "0.12.5"
serde = "1.0.70"
serde_derive = "1.0.70"