[package]
name = "likemark-cli"
version = "0.1.0"
authors = ["team-chiru <team-chiru@protonmail.com>"]

[dependencies]
clap = {version = "2.32", features = [ "yaml", "suggestions", "color" ]}
reqwest = "0.8.6"